# Generated by Django 4.2.4 on 2023-09-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='дата последнего изменения'),
        ),
    ]
